version: 2

jobs:
  build:

    working_directory: ~/helaar/reststop
    parallelism: 1
    shell: /bin/bash --login
    
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init

    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ .Branch }}-
        # Default branch if not
        - v1-dep-master-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1-dep-          
    - run: mvn install -DskipTests
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}   
    - run: bash <(curl -s https://copilot.blackducksoftware.com/ci/circle/scripts/upload)

