version: 2


jobs:
  build:

    working_directory: ~/helaar/reststop
    parallelism: 1
    shell: /bin/bash --login
    
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init

    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run: mvn install -DskipTests
    - run: bash <(curl -s https://copilot.blackducksoftware.com/ci/circle/scripts/upload)
